site_name: FastHX
repo_name: volfpeter/fasthx
repo_url: https://github.com/volfpeter/fasthx

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - Examples:
      - Examples: examples/index.md
      - examples/htmy.md
      - examples/jinja-templating.md
      - examples/custom-templating.md
  - API Reference:
      - api/core-decorators.md
      - Component Selectors: api/component_selectors.md
      - HTMY: api/htmy.md
      - api/jinja.md
      - api/dependencies.md
      - api/typing.md
  - Migrations:
      - migrations/1-to-2.md
